version: "3.8"

services:
  node-app:
    volumes:
      - .:/app:ro
      - /app/node_modules
    environment:
      - NODE_ENV=development
    command: npm run dev

# docker compose -f docker-compose.yaml -f docker-compose-dev.yaml up -d
