version: "3.8"

services:
  nginx:
    image: nginx:stable-alpine
    ports:
      - "3000:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
  node-app:
    build: .
    environment:
      - PORT=3000
    depends_on:
      - mongo # this will make sure that mongo started first before node
      - redis
      - nginx
    deploy:
      resources:
        limits:
          cpus: "0.25"
          memory: 250M
  mongo:
    image: mongo:latest
    volumes:
      - mongo-data:/data/db # make volume for keeping database mongo
    deploy:
      resources:
        limits:
          cpus: "0.3"
          memory: 300M
  redis:
    image: redis
    deploy:
      resources:
        limits:
          cpus: "0.2"
          memory: 200M
volumes:
  mongo-data:
